### PR TITLE
SpiGot 1.13 API update

### LINKED ISSUE #142: [Documentation] Bad URL in the repository description.
The current repository description has an old URL that directs to a 404 on dev.bukkit.org.

Invalid URL: `https://dev.bukkit.org/server-mods/hyperconomy`
Valid URL: `https://dev.bukkit.org/projects/hyperconomy`

You can blame Curse / Twitch for this one...

### LINKED ISSUE #143: SpiGot/Craftbukkit API update for minecraft 1.13
Hi,

the SpiGot API is being updated to the new Minecraft version, which invalidates large amounts of the code. (https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-pre7-development-builds.328883/) 
There is also quite an amount of new Items to support.

Are going to update HC to 1.13? If yes, any ETA?

~~I'd help, but I can't get eclipse to properly load the project, because of the dependencies (which can't be updated or fixed for some reason)~~ Got it working see PR

Corresponding PR: #149 

Greetings

### LINKED ISSUE #148: Project is still configured for Java 1.6
The Project is still configured for Java 1.6. Minecraft 1.12 enforces a minimum version of Java 1.8

### LINKED ISSUE #150: Mobs can pickup Items in item displays

### LINKED ISSUE #153: ClassLoading like that no longer valid with spigot 1.13
https://github.com/RegalOwl/HyperConomy/blob/424200b94fd2fb57364a5f36e927ee040e2d480b/src/main/java/regalowl/hyperconomy/util/LibraryManager.java#L227-L237

After fixing the code in https://github.com/RegalOwl/HyperConomy/pull/149/commits/d45783bad3faeab1aab65e54a157493f76134a14 in #149

Spigot warns (as described in the blog post about 1.13), that the functionality is no longer valid and will be prohibited once released:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by regalowl.hyperconomy.util.LibraryManager (file:/B:/spigotmc_1.13/server/plugins/hyperconomy-0.975.8-SNAPSHOT.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of regalowl.hyperconomy.util.LibraryManager
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Additionally using the old (before my commit, so the way it is now) method with Java 8 in spigot 1.13 (after fixing the NBTTools) yields classpath errors, that prevent the server from accessing its classes and then crashing with pseudo random `java.lang.ClassDefNotFoundException`s (depending on when the first library is loaded)
Example Log1: https://pastebin.com/RWKRhyzm
Example Log2: https://pastebin.com/Pndn5TvH

Greetings

### PR DESCRIPTION
**Pull request by Pingger**
Updates several classes to work with the updated API of spigot and CB

Please review the changes made before merging, since some of them WILL break serialization and simple updating.

Fixes #142
Fixes #143
Fixes #148 
Fixes #150 
Fixes #153

### CODE REVIEW

**Comment by Pingger** [comment]
Known Issues: 
Enchantments need to be updated in the CSV
new Items not yet added (neither Mats, Points, nor Enchantments) (What to do with Cursed enchantments?)
~~https://pastebin.com/qvBPYjsv <- Something is wrong with the NBTTags. The method has been fundamentally changed~~
~~https://pastebin.com/GqK9xB2P <- Hacky ClassLoader code, that no longer works (works until Java 8, not working with Java 9)~~
~~Resulting in unusable commands~~

**Comment by Pingger** [comment]
@RegalOwl I'm done for now.
~~I don't know what the CMethod in NBTTools should do and therefore can't fix that.~~ Found the method by comparing the mc server source codes
~~And I don't really understand what that ClassLoader Code in the LibraryManager tries to accomplish (Java 9 issue)~~ Fixed by using the intended java way of loading libraries

**Comment by Pingger** [comment]
Ready to merge

**Comment by PurpleStormCloud** [comment]
Well this is certainly interesting xD welp I might have done work for nothing now. Well if you can call it that.... Is there at least anything useful we can take from this? What I did there works without issues afaik (I didn't used Maven so I didn't update any refs) have been running it in production for a while without issues https://github.com/RegalOwl/HyperConomy/pull/156

**Comment by PurpleStormCloud** [comment]
One thing we could do is that we could use Material.values() for the items instead the csv, and for enchanting and stuff, that might be a good idea for the future? I get that its for the price but there should be possibly a better solution to that ....

**Pull request closed without merging**
