### PR TITLE
Added Tax exemption permission (hyperconomy.taxexempt)

### PR DESCRIPTION
**Pull request by Articdive**
The Permission defaults to true for admins and is defaulted false for standard players

### CODE REVIEW

**Comment by Articdive** [comment]
Did something small the project is quite big and hard to understand however im getting the hang of it

**Comment by Articdive** [comment]
Closes #43

**Comment by RegalOwl** [comment]
I can give you an overview of the project.  I might have time during the next few days to write one.  This looks good.

**Comment by Articdive** [comment]
Alright let me know just directly add me on Discord (Articdive#4078) or Skype: Articdive

**Pull request merged**
